# Keypad
bindkey -s "Op" "0"
bindkey -s "Oq" "1"
bindkey -s "Or" "2"
bindkey -s "Os" "3"
bindkey -s "Ot" "4"
bindkey -s "Ou" "5"
bindkey -s "Ov" "6"
bindkey -s "Ow" "7"
bindkey -s "Ox" "8"
bindkey -s "Oy" "9"

bindkey -s "On" "."
bindkey -s "Oo" "/"
bindkey -s "Oj" "*"
bindkey -s "Om" "-"
bindkey -s "OM" "^M"
