#!/bin/bash

# Shorthand
alias c='clear'
alias ct='cleartool'
alias ctsv='cleartool setview'
alias h='history'
alias hgrep='history | grep'
alias ll='ls -l'
alias vdiff='vimdiff'
alias gdiff='git diff -U0 --patience --minimal --word-diff'
alias vi='vim'

# Extend existing commands
alias gcc='gcc -Wall'
alias grep='grep --color=auto -n'
alias egrep='egrep --color=auto -n'
alias less='less -r'
alias more='less -r' # More is less...?
alias subl='subl -n'
alias tree='tree -C'
alias du='du -h'

# New commands
alias myip="ifconfig eth0 | \grep inet | grep -v inet6 | cut -d':' -f2 | cut -d' ' -f1"
alias reload="source $HOME/.bashrc"

# Platform specific aliases
case "$OSTYPE" in
    win32 | cygwin)         # Windows
        # FIXME: Often ends up trying to open a nonexisting .../cygdrive/... path
        #   - Tilde expansion doesn't work
        #   - Symlinks don't work
        alias subl="c:/Program\ Files/Sublime\ Text\ 2/sublime_text.exe -n"

        alias ls='ls -Fh --color=auto --group-directories-first --time-style=+"%b %e %Y %_I:%M%P"'
        alias open='cygstart'
        ;;
    darwin*)                # Mac
        alias ls='ls -FGh'
        ;;
    linux-gnu | freebsd)    # Linux
        alias ls='ls -Fh --color=auto --group-directories-first --time-style=+"%b %e %Y %_I:%M%P"'
        ;;
esac

# Retired
# alias cs='ssh eshahar@cs.uml.edu'
# alias tunnel='screen -d -m -S tunnel ssh -C2qTnN -D 8080 eshahar@cs.uml.edu'
